routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BookModelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});

Route::resource('Book', BookModelController::class);



// Route::get('/books/{$id}', [
//     'as'	=>	'books-get',
//     'uses'	=>	'BookModelController@getBookList'
// ]);

app/Models/BookModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BookModel extends Model
{
    use HasFactory;


    // protected $table = "book_models";
    
	// public $timestamps = false;

    protected $table = 'books';
    public $timestamps = true;
    protected $guarded = ['id'];


   

    protected $fillable = [
        'name',
        'publisher',
        'author',
        'stock'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookModelController.php
<?php

namespace App\Http\Controllers;

use App\Models\BookModel;
use Illuminate\Http\Request;

class BookModelController extends Controller
{
    // public function postAdminGroupCreate(){
	// 	$input = request()->all();

	// 	$validator = \Validator::make($input['data'], (new BookModel)->getRule());

    //     if($validator->fails()) {
    //         \Session::flash('friendly-error-msg', 'There are some validation errors');
    //         return redirect()->back()
    //                         ->withInput()
    //                         ->withErrors($validator);
    //     }

	// 	BookModel::create([
	// 		'name' => $input['data']['name']
	// 	]);

	// 	session()->flash('success-msg', 'User group successfully created');

	// 	return redirect()->back();
	// }





    // public function getBookList($id){
    //     $groups = BookModel::where('id', $id)->with('Book')->get();
	// 	// return $groups;

	// 	return view($this->view.'list-member')
	// 		->with('id', $id);

    // }

    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $book = BookModel::latest()->paginate(5);

        return view('Book.index', compact('book'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('Book.create');
    }


    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'publisher' => 'required',
            'author' => 'required',
            'stock' => 'required'
        ]);

        BookModel::create($request->all());

        return redirect()->route('Book.index')
            ->with('success', 'Project created successfully.');
    }


    /**
     * Display the specified resource.
     *
     */
    public function show(BookModel $book)
    {
        return view('Book.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     */
    public function edit(BookModel $book)
    {
        return view('Book.edit', compact('book'));
    }


    /**
     * Update the specified resource in storage.
     *
     */
    public function update(Request $request, BookModel $book)
    {
        $request->validate([
            'name' => 'required',
            'publisher' => 'required',
            'author' => 'required',
            'stock' => 'required'
        ]);
        $book->update($request->all());

        return redirect()->route('Book.index')
            ->with('success', 'Project updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     */
    public function destroy(BookModel $book)
    {
        $book->delete();

        return redirect()->route('Book.index')
            ->with('success', 'Project deleted successfully');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/Book/Create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Book</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('Book.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('Book.store') }}" method="POST" >
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Publisher:</strong>
                    <textarea class="form-control" style="height:50px" name="publisher"
                        placeholder="Publisher"></textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Author:</strong>
                    <input type="text" name="author" class="form-control" placeholder="Author">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Stock:</strong>
                    <input type="number" name="stock" class="form-control" placeholder="Stock">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/Book/Edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Books</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('Book.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('Book.update', $book->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $book->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Publisher:</strong>
                    <textarea class="form-control" style="height:50px" name="publisher"
                        placeholder="Publisher">{{ $book->publisher }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>author:</strong>
                    <input type="text" name="author" class="form-control" placeholder="{{ $book->author }}"
                        value="{{ $book->author }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Stock:</strong>
                    <input type="number" name="stock" class="form-control" placeholder="{{ $book->stock }}"
                        value="{{ $book->stock }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/Book/Index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 8 CRUD </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('Book.create') }}" title="Insert a book"> <i class="fas fa-plus-circle"></i>
                    </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Publisher</th>
            <th>Author</th>
            <th>Stock</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($book as $index => $d)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $d->name }}</td>
                <td>{{ $d->publisher }}</td>
                <td>{{ $d->author }}</td>
                <td>{{ $d->stock }}</td>
                <td>
                    <form action="{{ route('Book.destroy', $book->id) }}" method="POST">

                        <a href="{{ route('Book.show', $book->id) }}" title="show">
                            <i class="fas fa-eye text-success  fa-lg"></i>
                        </a>

                        <a href="{{ route('Book.edit', $book->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>

                        </a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" title="delete" style="border: none; background-color:transparent;">
                            <i class="fas fa-trash fa-lg text-danger"></i>

                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    {!! $books->links() !!}

@endsection

resources/views/Book/Show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>  {{ $book->name }} </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('Book.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $book->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Publisher:</strong>
                {{ $book->publisher }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Author:</strong>
                {{ $book->author }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Stock:</strong>
                {{ $book->stock }}
            </div>
        </div>
    </div>
@endsection

resources/views/Layouts/app.blade.php
<html>

<head>
    <title>App Name - @yield('title')</title>

    <!-- Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #9C27B0;
            color: white;
            text-align: center;
        }

    </style>

</head>

<body>
    @section('sidebar')

    @show

    <div class="container">
        @yield('content')
   
</body>

</html>

resources/views/list-book.blade.php
<h1 class="h3 mb-4 text-gray-800">List of Books</h1>

	

	<div class="table-responsive">
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>SN</th>
					<th>Book Name</th>
					<th>Publisher</th>
					<th>Author</th>
                    <th>Stock</th>
				</tr>
			</thead>
            <tbody>
				
				
			
			</tbody>
		</table>
	</div>
	